In [33]:
import pandas as pd
import csv
reader = csv.reader(open('tdoc.csv', 'r'))
docs = {}
for row in reader:
   k, v = row
   docs[k] = v
docs

{'Document 1': 'This is the first document. It contains some words.',
 'Document 2': 'The second document is a bit longer and has different words.',
 'Document 3': 'The third document is short. Short documents can be concise.'}

In [35]:
content_list = [content for content in docs.values()]  
content_list

['This is the first document. It contains some words.',
 'The second document is a bit longer and has different words.',
 'The third document is short. Short documents can be concise.']

In [36]:
# Gather the set of all unique terms from the list content of document and diplay the result

unique_terms = {term for doc in content_list for term in doc.split()}
print(unique_terms)

{'and', 'short.', 'has', 'first', 'different', 'a', 'third', 'longer', 'document', 'documents', 'words.', 'bit', 'This', 'concise.', 'can', 'Short', 'be', 'is', 'the', 'contains', 'document.', 'some', 'It', 'The', 'second'}


In [38]:
# create a matrix for the document by using the unique term
doc_term_matrix = {}

# your code here
for term in unique_terms:
    doc_term_matrix[term] = []
    for doc in content_list:
        doc_term_matrix[term].append(1) if term in doc else doc_term_matrix[term].append(0)

# display the result of the matrix
doc_term_matrix

{'and': [0, 1, 0],
 'short.': [0, 0, 1],
 'has': [0, 1, 0],
 'first': [1, 0, 0],
 'different': [0, 1, 0],
 'a': [1, 1, 1],
 'third': [0, 0, 1],
 'longer': [0, 1, 0],
 'document': [1, 1, 1],
 'documents': [0, 0, 1],
 'words.': [1, 1, 0],
 'bit': [0, 1, 0],
 'This': [1, 0, 0],
 'concise.': [0, 0, 1],
 'can': [0, 0, 1],
 'Short': [0, 0, 1],
 'be': [0, 0, 1],
 'is': [1, 1, 1],
 'the': [1, 0, 0],
 'contains': [1, 0, 0],
 'document.': [1, 0, 0],
 'some': [1, 0, 0],
 'It': [1, 0, 0],
 'The': [0, 1, 1],
 'second': [0, 1, 0]}

In [42]:
# import the numpy library if it doesn't work you need to install numpy
import numpy as np

docs_array = np.array(content_list, dtype='object')

v1 = np.array(doc_term_matrix['first'])    
v2 = np.array(doc_term_matrix['document'])

print(v1)
print(v2)
print('-------')

# find the documents that have both terms from v1 and v2
v3 = v1 & v2

print(v3)

# display the content document from the result
result = [doc for doc in v3 * docs_array if doc]
print(result)

[1 0 0]
[1 1 1]
-------
[1 0 0]
['This is the first document. It contains some words.']


In [43]:
keys_result = set()
for i,x in docs.items():
    if x in result:
        keys_result.add(i)
print(keys_result)

{'Document 1'}


In [44]:
import csv

# Convert the set to a list
my_list = list(unique_terms)

# Specify the CSV file path
csv_file_path = 'my_set.csv'

# Write the data to the CSV file
with open(csv_file_path, 'w', newline='') as csv_file:
    csv_writer = csv.writer(csv_file)
    
    # Write the data as a single row
    csv_writer.writerow(my_list)

print(f"Set saved as {csv_file_path}")

Set saved as my_set.csv
